name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize ]
jobs:
  if: ${{ github.ref == 'refs/heads/master' }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "stanny-pokedex"
          heroku_email: "holydonk@gmail.com"
          healthcheck: "https://stanny-pokedex.herokuapp.com/health"
          rollbackonhealthcheckfailed: true